[workspace]
resolver = "3"
members = [
    "audio-conversion",
    "audio-conversion/plugin",
    "audio-effects",
    "image-conversion",
    "image-conversion/plugin",
    "image-transformation",
    "media-streaming",
    "media-streaming/plugin",
    "video-conversion",
    "video-conversion/plugin",
    "video-transformation",
]

[workspace.dependencies]
ppff-audio-conversion = { path = "audio-conversion", version = "0.1.0", package = "ppff-audio-conversion" }
ppff-image-conversion = { path = "image-conversion", package = "ppff-image-conversion" }
ppff-media-streaming = { path = "media-streaming", package = "ppff-media-streaming" }
ppdrive = "0.2.0"
serde = "1.0.229"
serde_json = "1.0.151"
ppff-video-conversion = { path = "video-conversion", version = "0.1.0", package = "ppff-video-conversion" }

[profile.release]
strip = "symbols"
